//
//  UIColor+Man Up.swift
//
//  Generated by Zeplin on 12/3/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

import UIKit

extension UIColor {
    
    class func colorWithGray(gray: Int) -> UIColor {
      return UIColor(red: CGFloat(gray) / 255.0, green: CGFloat(gray) / 255.0, blue: CGFloat(gray) / 255.0, alpha: 1.0)
    }
    
    class func colorWithRGB(r r: Int, g: Int, b: Int) -> UIColor {
        return UIColor(red: CGFloat(r) / 255.0, green: CGFloat(g) / 255.0, blue: CGFloat(b) / 255.0, alpha: 1.0)
    }
    
    // MARK: Grey Colors
    class func scHeaderColor() -> UIColor {
        return UIColor(red: 24.0 / 255.0, green: 120.0 / 255.0, blue: 166.0 / 255.0, alpha: 1.0)
    }
    
    class func muBlack25Color() -> UIColor {
        return UIColor(red: 0.0 / 255.0, green: 0.0 / 255.0, blue: 0.0 / 255.0, alpha: 0.25)
    }

    }
